---
engines:
  phpcs:
    enabled: true
    exclude_paths:
      # CLI-Scripts haben andere Standards als Web-Code
      - 'backend/cleanup.php'
      - 'backend/worker.php'

exclude_paths:
  - 'node_modules/**'
  - 'dist/**'
  - 'backend/temp/**'
  - 'backend/queue.db'

# Deaktiviere übermäßig strenge Regeln
checks:
  # Diese Funktionen sind in unserem Kontext sicher und notwendig
  Security.BadFunctions.CallbackFunctions.WarnFwrite:
    enabled: false  # fwrite() ist die RICHTIGE Methode für CLI-Output
  Security.BadFunctions.EasyRFI.WarnEasyRFI:
    enabled: false  # require für lokale Config-Dateien ist OK
  Security.BadFunctions.Asserts.WarnAssert:
    enabled: false
  Generic.PHP.NoSilencedErrors.Discouraged:
    enabled: false

  # Diese sind für CLI-Scripts notwendig
  Security.BadFunctions.CallbackFunctions.WarnSleep:
    enabled: false  # sleep() notwendig für Worker-Loop
  Security.BadFunctions.SystemExecFunctions.WarnExec:
    enabled: false  # exec() für FFmpeg notwendig, mit escapeshellarg() gesichert
  Security.BadFunctions.FilesystemFunctions.WarnGlob:
    enabled: false  # glob() sicher für Dateiliste
  Security.BadFunctions.FilesystemFunctions.WarnIsDir:
    enabled: false  # is_dir() normale PHP-Funktion
  Security.BadFunctions.FilesystemFunctions.WarnFilesize:
    enabled: false  # filesize() normale PHP-Funktion
  Security.BadFunctions.FilesystemFunctions.WarnFileGetContents:
    enabled: false  # file_get_contents() nur für lokale JSON-Dateien

  # escapeshellarg() ist SICHER, nicht gefährlich!
  Security.BadFunctions.SystemExecFunctions.WarnEscapeShellArg:
    enabled: false  # escapeshellarg() verhindert Injection!
